apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    # image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
    image: chriaass/activemq-artemis-broker-kubernetes:latest
    initImage: chriaass/artemis-basic-init
    enableMetricsPlugin: true
  console:
    expose: true
  adminUser: admin
  adminPassword: password